In [1]:
from pyquil import Program, get_qc
from pyquil.gates import *
import numpy as np

A function f:{0, 1} -> {0, 1} may be constant (equal to the same value for both its inputs), or balanced (equal to one value for one of its inputs, and the other value for the other input). The quantum algorithm to determine whether the function is constant/balanced is known as Deutsch's algorithm. We have the following 4 possibilities for this function:<br>
<br>
(a) f(0) = 0 ; f(1) = 0 <br>
(b) f(0) = 1 ; f(1) = 1 <br>
(c) f(0) = 0 ; f(1) = 1 <br>
(d) f(0) = 1 ; f(1) = 0 <br>
<br>
The action fo the black-box unitary operator is in general given by <br>
<br>
$$U_f : \vert x \rangle \vert y \rangle \rightarrow \vert x \rangle \vert y \oplus f(x) \rangle$$<br>
so that the actions of the black-box unitary operator corresponding to each of the above four cases are respectively<br>
<br>
(a) $U_f : \vert 0 \rangle \vert 0 \rangle \rightarrow \vert 0 \rangle \vert 0 \rangle  \qquad\qquad\qquad\qquad(b)\,U_f : \vert 0 \rangle \vert 0 \rangle \rightarrow \vert 0 \rangle \vert 1 \rangle$ <br> 
$\quad U_f : \vert 0 \rangle \vert 1 \rangle \rightarrow \vert 0 \rangle \vert 1 \rangle  \qquad\qquad\qquad\qquad\quad\, U_f : \vert 0 \rangle \vert 1 \rangle \rightarrow \vert 0 \rangle \vert 0 \rangle$ <br>
$\quad U_f : \vert 1 \rangle \vert 0 \rangle \rightarrow \vert 1 \rangle \vert 0 \rangle  \qquad\qquad\qquad\qquad\quad\,  U_f : \vert 1 \rangle \vert 0 \rangle \rightarrow \vert 1 \rangle \vert 1 \rangle$ <br>
$\quad U_f : \vert 1 \rangle \vert 1 \rangle \rightarrow \vert 1 \rangle \vert 1 \rangle  \qquad\qquad\qquad\qquad\quad\,  U_f : \vert 1 \rangle \vert 1 \rangle \rightarrow \vert 1 \rangle \vert 0 \rangle$ <br>
<br>
(c) $U_f : \vert 0 \rangle \vert 0 \rangle \rightarrow \vert 0 \rangle \vert 0 \rangle  \qquad\qquad\qquad\qquad(d)\,U_f : \vert 0 \rangle \vert 0 \rangle \rightarrow \vert 0 \rangle \vert 1 \rangle$ <br> 
$\quad U_f : \vert 0 \rangle \vert 1 \rangle \rightarrow \vert 0 \rangle \vert 1 \rangle  \qquad\qquad\qquad\qquad\quad\, U_f : \vert 0 \rangle \vert 1 \rangle \rightarrow \vert 0 \rangle \vert 0 \rangle$ <br>
$\quad U_f : \vert 1 \rangle \vert 0 \rangle \rightarrow \vert 1 \rangle \vert 1 \rangle  \qquad\qquad\qquad\qquad\quad\,  U_f : \vert 1 \rangle \vert 0 \rangle \rightarrow \vert 1 \rangle \vert 0 \rangle$ <br>
$\quad U_f : \vert 1 \rangle \vert 1 \rangle \rightarrow \vert 1 \rangle \vert 0 \rangle  \qquad\qquad\qquad\qquad\quad\,  U_f : \vert 1 \rangle \vert 1 \rangle \rightarrow \vert 1 \rangle \vert 1 \rangle$ <br>

__Exercise__: Construct the black-box unitary operators for each of the above 4 cases

In [5]:
def black_box_a():
    """
    :return: array representing the black-box operator of case (a) described above
    """
    return np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])

q00 = np.array([1, 0, 0, 0])[:, np.newaxis]
q00 = np.kron(q00, q00.T)

q01 = np.array([])

op = black_box_a()

q_new = op.dot(q00.dot(np.conjugate(op.T)))
print(q_new)


[[1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [7]:
def black_box_b():
    """
    :return: array representing the black-box operator of case (b) described above
    """
    return np.array([[0, 1, 0, 0], [1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]])

q00 = np.array([1, 0, 0, 0])[:, np.newaxis]
q00 = np.kron(q00, q00.T)

op = black_box_b()

q_new = op.dot(q00.dot(np.conjugate(op.T)))
print(q_new)

[[0 0 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
def black_box_c():
    """
    :return: array representing the black-box operator of case (c) described above
    """
    # TODO

In [ ]:
def black_box_d():
    """
    :return: array representing the black-box operator of case (b) described above
    """
    # TODO

__Exercise__: Construct a Propram that will prepare initial state, i.e. the state upto (but excluding) the application of the black-box operator, given by $\vert \psi \rangle_{\text{init}} = \frac{1}{\sqrt{2}} \left( \vert 0 \rangle + \vert 1 \rangle \right) \otimes \frac{1}{\sqrt{2}} \left( \vert 0 \rangle - \vert 1 \rangle \right)$.

In [ ]:
def init_state():
    """
    :return: Program programming the initial state, on which the black-box operator will act
    """
    # TODO

In [ ]:
qc = get_qc('9q-generic-qvm')

In the case of a balanced function (situations (a) and (b)), a measurement of qubit 1 should always yield 0. In the case of a constant function (situations (c) and (d)), a measurement of qubit 1 should always yield 1. The gates in the circuit appearing after the application of the black-box operator have already been applied for you.

In [ ]:
# situation (a)
p = init_state()
p.defgate("U_f_a", black_box_a())
p.inst(("U_f_a", 1, 0))
p.inst(H(1))
resultA = qc.run_and_measure(p, trials=100)[1]
del p

# situation (b)

p = init_state()
p.defgate("U_f_b", black_box_b())
p.inst(("U_f_b", 1, 0))
p.inst(H(1))
resultB = qc.run_and_measure(p, trials=100)[1]
del p

# situation (c)

p = init_state()
p.defgate("U_f_c", black_box_c())
p.inst(("U_f_c", 1, 0))
p.inst(H(1))
resultC = qc.run_and_measure(p, trials=100)[1]
del p

# situation (d)

p = init_state()
p.defgate("U_f_d", black_box_d())
p.inst(("U_f_d", 1, 0))
p.inst(H(1))
resultD = qc.run_and_measure(p, trials=100)[1]
del p

In [ ]:
# tests ensuring results are sound
np.testing.assert_equal(np.unique(resultA), [0])
np.testing.assert_equal(np.unique(resultB), [0])
np.testing.assert_equal(np.unique(resultC), [1])
np.testing.assert_equal(np.unique(resultD), [1])

print("Tests have passed!")